-- Phase 8 hierarchy fields were already introduced in
-- 20260326140000_phase8_wiki_hierarchy_legacy. This migration is intentionally
-- kept as a no-op to preserve history without reapplying the same DDL.
