export type CompendiumKind = 'BESTIARY' | 'SPELL' | 'ITEM' | 'CLASS';

export type CompendiumSource = 'SRD' | 'OGL' | 'LEGACY';

export interface CompendiumEntry {
  id: string;
  systemSlug: string;
  kind: CompendiumKind;
  name: string;
  summary: string;
  tags: string[];
  source: CompendiumSource;
  payload: Record<string, unknown>;
}

export interface FilterCompendiumInput {
  systemSlug: string;
  kind?: CompendiumKind;
  search?: string;
  limit: number;
}

const ENTRIES: CompendiumEntry[] = [
  {
    id: 'dnd5e-class-wizard',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Wizard',
    summary: 'Conjurador arcano versatil com foco em grimorios e escolas de magia.',
    tags: ['arcane', 'intelligence', 'caster'],
    source: 'SRD',
    payload: { hitDie: 'd6', primaryAbility: 'INT' },
  },
  {
    id: 'dnd5e-class-fighter',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Fighter',
    summary: 'Especialista marcial versatil com grande sobrevivencia em combate.',
    tags: ['martial', 'frontline', 'strength'],
    source: 'SRD',
    payload: { hitDie: 'd10', primaryAbility: 'STR/DEX' },
  },
  {
    id: 'dnd5e-class-cleric',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Cleric',
    summary: 'Canaliza poder divino para suporte, cura e controle de campo.',
    tags: ['divine', 'support', 'wisdom'],
    source: 'SRD',
    payload: { hitDie: 'd8', primaryAbility: 'WIS' },
  },
  {
    id: 'dnd5e-class-rogue',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Rogue',
    summary: 'Especialista em infiltracao, armadilhas e pressao tatica com mobilidade alta.',
    tags: ['stealth', 'dexterity', 'skill'],
    source: 'SRD',
    payload: { hitDie: 'd8', primaryAbility: 'DEX' },
  },
  {
    id: 'dnd5e-class-subclass-evocation',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Wizard - School of Evocation',
    summary: 'Subclasse focada em explosao arcana e modelagem de dano em area.',
    tags: ['subclass', 'wizard', 'evocation'],
    source: 'SRD',
    payload: { classType: 'subclass', parentClass: 'Wizard' },
  },
  {
    id: 'dnd5e-class-subclass-battle-master',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Fighter - Battle Master',
    summary: 'Subclasse tatica baseada em manobras e controle do ritmo de combate.',
    tags: ['subclass', 'fighter', 'maneuvers'],
    source: 'SRD',
    payload: { classType: 'subclass', parentClass: 'Fighter' },
  },
  {
    id: 'dnd5e-class-ancestry-elf',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Ancestry - Elf',
    summary: 'Ancestral agil com percepcao elevada e afinidade arcana.',
    tags: ['ancestry', 'elf', 'agility'],
    source: 'SRD',
    payload: { classType: 'ancestry', speed: 30 },
  },
  {
    id: 'dnd5e-class-ancestry-dwarf',
    systemSlug: 'dnd5e',
    kind: 'CLASS',
    name: 'Ancestry - Dwarf',
    summary: 'Ancestral resistente com foco em vigor e disciplina cultural.',
    tags: ['ancestry', 'dwarf', 'resilience'],
    source: 'SRD',
    payload: { classType: 'ancestry', speed: 25 },
  },
  {
    id: 'dnd5e-spell-fireball',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Fireball',
    summary: 'Explosao de fogo em area com alto dano e impacto tatico.',
    tags: ['evocation', 'aoe', 'damage'],
    source: 'SRD',
    payload: { level: 3, school: 'Evocation', range: '150 feet' },
  },
  {
    id: 'dnd5e-spell-magic-missile',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Magic Missile',
    summary: 'Projeteis arcanos confiaveis que nao exigem teste de acerto.',
    tags: ['evocation', 'force', 'reliable'],
    source: 'SRD',
    payload: { level: 1, school: 'Evocation', range: '120 feet' },
  },
  {
    id: 'dnd5e-spell-counterspell',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Counterspell',
    summary: 'Resposta imediata para interromper magia inimiga e virar cenas de alto risco.',
    tags: ['abjuration', 'reaction', 'anti-magic'],
    source: 'SRD',
    payload: { level: 3, school: 'Abjuration', castTime: '1 reaction' },
  },
  {
    id: 'dnd5e-spell-detect-magic',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Detect Magic',
    summary: 'Ferramenta de investigacao arcana para cenas de pista, relicario e ritual.',
    tags: ['divination', 'utility', 'ritual'],
    source: 'SRD',
    payload: { level: 1, school: 'Divination', duration: 'Concentration, up to 10 minutes' },
  },
  {
    id: 'dnd5e-spell-shield',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Shield',
    summary: 'Reacao defensiva para evitar ataques e proteger contra magic missile.',
    tags: ['abjuration', 'reaction', 'defense'],
    source: 'SRD',
    payload: { level: 1, school: 'Abjuration', duration: '1 round' },
  },
  {
    id: 'dnd5e-spell-misty-step',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Misty Step',
    summary: 'Reposicionamento curto para fuga, infiltracao e pressao tatica em mapas apertados.',
    tags: ['conjuration', 'mobility', 'bonus-action'],
    source: 'SRD',
    payload: { level: 2, school: 'Conjuration', range: 'Self' },
  },
  {
    id: 'dnd5e-spell-revivify',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Revivify',
    summary: 'Retorna um aliado recem-caido, mudando o resultado de encontros letais.',
    tags: ['necromancy', 'resurrection', 'support'],
    source: 'SRD',
    payload: { level: 3, school: 'Necromancy', castTime: '1 action' },
  },
  {
    id: 'dnd5e-spell-legacy-frostborne-ember-ray',
    systemSlug: 'dnd5e',
    kind: 'SPELL',
    name: 'Frostborne Ember Ray',
    summary: 'Magia legado associada a Augustus Frostborne em cronicas de 2023.',
    tags: ['legacy', 'augustus', 'fire', 'ice'],
    source: 'LEGACY',
    payload: { level: 2, school: 'Evocation', trait: 'legacy-canon' },
  },
  {
    id: 'dnd5e-item-frostborne-star-compass',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Frostborne Star Compass',
    summary: 'Reliquia legado usada por Augustus para rastrear focos de energia e ruinas esquecidas.',
    tags: ['legacy', 'augustus', 'navigation', 'arcane'],
    source: 'LEGACY',
    payload: { rarity: 'Rare', effect: 'Reveals strong arcane signatures during exploration' },
  },
  {
    id: 'dnd5e-item-healing-potion',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Potion of Healing',
    summary: 'Pocao comum para recuperacao rapida de pontos de vida.',
    tags: ['consumable', 'healing'],
    source: 'SRD',
    payload: { rarity: 'Common', effect: '2d4+2 HP' },
  },
  {
    id: 'dnd5e-item-thieves-tools',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Thieves Tools',
    summary: 'Kit essencial para abrir fechaduras e desarmar armadilhas.',
    tags: ['tools', 'utility', 'rogue'],
    source: 'SRD',
    payload: { category: 'Tools', check: 'DEX (Thieves Tools)' },
  },
  {
    id: 'dnd5e-item-holy-symbol',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Holy Symbol',
    summary: 'Foco sagrado usado para canalizar poder divino em magias clericais.',
    tags: ['focus', 'divine', 'cleric'],
    source: 'SRD',
    payload: { category: 'Spellcasting Focus', classes: ['Cleric', 'Paladin'] },
  },
  {
    id: 'dnd5e-item-condition-poisoned',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Condition - Poisoned',
    summary: 'Desvantagem em ataques e testes de habilidade enquanto envenenado.',
    tags: ['condition', 'quick-reference', 'combat'],
    source: 'SRD',
    payload: { type: 'Condition', effect: 'Disadvantage on attack rolls and ability checks' },
  },
  {
    id: 'dnd5e-item-condition-frightened',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Condition - Frightened',
    summary: 'Nao pode se aproximar da fonte do medo e sofre desvantagem relevante.',
    tags: ['condition', 'quick-reference', 'mental'],
    source: 'SRD',
    payload: { type: 'Condition', effect: 'Cannot move closer and has disadvantage while source is visible' },
  },
  {
    id: 'dnd5e-item-rule-advantage-disadvantage',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Quick Rule - Advantage and Disadvantage',
    summary: 'Role 2d20, mantenha o maior para vantagem ou menor para desvantagem.',
    tags: ['rule', 'quick-reference', 'd20'],
    source: 'SRD',
    payload: { notation: ['2d20kh1', '2d20kl1'] },
  },
  {
    id: 'dnd5e-item-rule-opportunity-attack',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Quick Rule - Opportunity Attack',
    summary: 'Resumo do disparo de ataque ao sair do alcance inimigo sem disengage.',
    tags: ['rule', 'quick-reference', 'combat'],
    source: 'SRD',
    payload: { trigger: 'Leaving reach', exception: 'Disengage or forced movement' },
  },
  {
    id: 'dnd5e-item-rule-cover',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Quick Rule - Cover',
    summary: 'Cobertura parcial, meia e total para acelerar decisao em mapas e corredores.',
    tags: ['rule', 'quick-reference', 'defense'],
    source: 'SRD',
    payload: { bonuses: ['Half cover +2 AC/DEX', 'Three-quarters cover +5 AC/DEX', 'Total cover no target'] },
  },
  {
    id: 'dnd5e-item-legacy-satoru-night-mantle',
    systemSlug: 'dnd5e',
    kind: 'ITEM',
    name: 'Satoru Night Mantle',
    summary: 'Manto legado atribuido a Satoru Naitokira em cronicas originais.',
    tags: ['legacy', 'satoru', 'stealth'],
    source: 'LEGACY',
    payload: { rarity: 'Rare', bonus: '+2 on stealth checks at night' },
  },
  {
    id: 'dnd5e-bestiary-goblin',
    systemSlug: 'dnd5e',
    kind: 'BESTIARY',
    name: 'Goblin',
    summary: 'Humanoide pequeno, oportunista e perigoso em grupos.',
    tags: ['humanoid', 'low-cr'],
    source: 'SRD',
    payload: { cr: '1/4', xp: 50 },
  },
  {
    id: 'dnd5e-bestiary-owlbear',
    systemSlug: 'dnd5e',
    kind: 'BESTIARY',
    name: 'Owlbear',
    summary: 'Predador territorial brutal, excelente para encontros em floresta.',
    tags: ['monstrosity', 'mid-cr', 'forest'],
    source: 'SRD',
    payload: { cr: '3', xp: 700 },
  },
  {
    id: 'dnd5e-bestiary-lich',
    systemSlug: 'dnd5e',
    kind: 'BESTIARY',
    name: 'Lich',
    summary: 'Arquimago morto-vivo de altissimo risco e impacto de campanha.',
    tags: ['undead', 'high-cr', 'boss'],
    source: 'SRD',
    payload: { cr: '21', xp: 33000 },
  },
  {
    id: 'dnd5e-bestiary-young-red-dragon',
    systemSlug: 'dnd5e',
    kind: 'BESTIARY',
    name: 'Young Red Dragon',
    summary: 'Predador draconico agressivo para climas de guerra e devastacao.',
    tags: ['dragon', 'high-cr', 'fire'],
    source: 'SRD',
    payload: { cr: '10', xp: 5900 },
  },
  {
    id: 'coc7e-class-investigator',
    systemSlug: 'coc7e',
    kind: 'CLASS',
    name: 'Investigator Archetype',
    summary: 'Perfil narrativo para investigadores enfrentando o horror cosmico.',
    tags: ['investigation', 'horror'],
    source: 'OGL',
    payload: { sanityFocus: true },
  },
  {
    id: 'coc7e-class-occult-dilettante',
    systemSlug: 'coc7e',
    kind: 'CLASS',
    name: 'Occult Dilettante',
    summary: 'Arquétipo voltado a pesquisa esoterica e custo alto de sanidade.',
    tags: ['occult', 'research', 'sanity'],
    source: 'OGL',
    payload: { sanityFocus: true, riskProfile: 'High' },
  },
  {
    id: 'coc7e-class-ancestry-dream-touched',
    systemSlug: 'coc7e',
    kind: 'CLASS',
    name: 'Ancestry - Dream-Touched',
    summary: 'Linhagem opcional marcada por sonhos profeticos e fragilidade mental.',
    tags: ['ancestry', 'mythos', 'dream'],
    source: 'OGL',
    payload: { classType: 'ancestry', sanityModifier: -5 },
  },
  {
    id: 'coc7e-spell-elder-sign',
    systemSlug: 'coc7e',
    kind: 'SPELL',
    name: 'Elder Sign',
    summary: 'Ritual de protecao contra entidades do Mythos.',
    tags: ['ritual', 'ward', 'mythos'],
    source: 'OGL',
    payload: { cost: 'Sanity + POW', castTime: 'Hours' },
  },
  {
    id: 'coc7e-spell-bind-byakhee',
    systemSlug: 'coc7e',
    kind: 'SPELL',
    name: 'Bind Byakhee',
    summary: 'Ritual perigoso para invocar e prender criatura do Mythos.',
    tags: ['ritual', 'summon', 'mythos'],
    source: 'OGL',
    payload: { cost: 'SAN + POW', castTime: 'Night ritual' },
  },
  {
    id: 'coc7e-item-mythos-tome',
    systemSlug: 'coc7e',
    kind: 'ITEM',
    name: 'Mythos Tome',
    summary: 'Compendio proibido que concede conhecimento e cobra sanidade.',
    tags: ['book', 'mythos', 'sanity'],
    source: 'OGL',
    payload: { skillGain: 'Cthulhu Mythos', sanityLoss: '1d6' },
  },
  {
    id: 'coc7e-item-forensic-kit',
    systemSlug: 'coc7e',
    kind: 'ITEM',
    name: 'Forensic Kit',
    summary: 'Ferramentas de investigacao para cenas de crime e coleta de provas.',
    tags: ['investigation', 'tools', 'detective'],
    source: 'OGL',
    payload: { bonus: '+20% Forensics in proper setup' },
  },
  {
    id: 'coc7e-item-condition-temp-insanity',
    systemSlug: 'coc7e',
    kind: 'ITEM',
    name: 'Condition - Temporary Insanity',
    summary: 'Perda aguda de controle por curto periodo apos choque mental.',
    tags: ['condition', 'sanity', 'quick-reference'],
    source: 'OGL',
    payload: { trigger: 'High sanity loss in short window' },
  },
  {
    id: 'coc7e-item-condition-bout-madness',
    systemSlug: 'coc7e',
    kind: 'ITEM',
    name: 'Condition - Bout of Madness',
    summary: 'Episodio imediato de insanidade com comportamento imprevisivel.',
    tags: ['condition', 'madness', 'quick-reference'],
    source: 'OGL',
    payload: { duration: '1d10 rounds', outcome: 'Keeper-defined behavior' },
  },
  {
    id: 'coc7e-item-rule-sanity-loss',
    systemSlug: 'coc7e',
    kind: 'ITEM',
    name: 'Quick Rule - Sanity Loss Check',
    summary: 'Rolagem padrao para perda de sanidade em encontros com o Mythos.',
    tags: ['rule', 'sanity', 'quick-reference'],
    source: 'OGL',
    payload: { notation: '1d100 under SAN', outcomes: ['No loss', 'Partial loss', 'Major loss'] },
  },
  {
    id: 'coc7e-bestiary-deep-one',
    systemSlug: 'coc7e',
    kind: 'BESTIARY',
    name: 'Deep One',
    summary: 'Criatura anfibia ancestral serva de cultos marinhos.',
    tags: ['mythos', 'amphibious'],
    source: 'OGL',
    payload: { threat: 'Major', sanityLoss: '1d6/1d20' },
  },
  {
    id: 'coc7e-bestiary-byakhee',
    systemSlug: 'coc7e',
    kind: 'BESTIARY',
    name: 'Byakhee',
    summary: 'Criatura alada serva de entidades exteriores, ideal para terror cosmico.',
    tags: ['mythos', 'flying', 'horror'],
    source: 'OGL',
    payload: { threat: 'High', sanityLoss: '1d6/1d20' },
  },
  {
    id: 'coc7e-bestiary-shoggoth',
    systemSlug: 'coc7e',
    kind: 'BESTIARY',
    name: 'Shoggoth',
    summary: 'Massa amorfa devastadora, encontro de fim de arco para grupos experientes.',
    tags: ['mythos', 'apex-threat', 'horror'],
    source: 'OGL',
    payload: { threat: 'Extreme', sanityLoss: '1d10/1d100' },
  },
  {
    id: 'tormenta20-class-arcanista',
    systemSlug: 'tormenta20',
    kind: 'CLASS',
    name: 'Arcanista',
    summary: 'Especialista em magias com alto teto de poder arcano.',
    tags: ['mana', 'arcano'],
    source: 'OGL',
    payload: { primaryAbility: 'INT', resource: 'Mana' },
  },
  {
    id: 'tormenta20-class-guerreiro',
    systemSlug: 'tormenta20',
    kind: 'CLASS',
    name: 'Guerreiro',
    summary: 'Especialista em combate direto, foco em consistencia e dano sustentado.',
    tags: ['martial', 'frontline', 'tormenta20'],
    source: 'OGL',
    payload: { primaryAbility: 'FOR', resource: 'Tecnicas' },
  },
  {
    id: 'tormenta20-class-subclass-cavaleiro-rubi',
    systemSlug: 'tormenta20',
    kind: 'CLASS',
    name: 'Subclasse - Cavaleiro de Rubi',
    summary: 'Arquetipo focado em disciplina, honra e controle de campo.',
    tags: ['subclass', 'cavaleiro', 'tatica'],
    source: 'OGL',
    payload: { classType: 'subclass', parentClass: 'Guerreiro' },
  },
  {
    id: 'tormenta20-class-ancestry-elfo',
    systemSlug: 'tormenta20',
    kind: 'CLASS',
    name: 'Ancestral - Elfo',
    summary: 'Ancestral agil e magico, com foco em precisao e mobilidade.',
    tags: ['ancestral', 'elfo', 'agilidade'],
    source: 'OGL',
    payload: { classType: 'ancestry', bonus: '+2 Destreza' },
  },
  {
    id: 'tormenta20-spell-bola-de-fogo',
    systemSlug: 'tormenta20',
    kind: 'SPELL',
    name: 'Bola de Fogo',
    summary: 'Magia ofensiva classica com dano em area.',
    tags: ['fogo', 'area', 'mana'],
    source: 'OGL',
    payload: { circle: 2, cost: 3 },
  },
  {
    id: 'tormenta20-spell-cura-pelas-maos',
    systemSlug: 'tormenta20',
    kind: 'SPELL',
    name: 'Cura Pelas Maos',
    summary: 'Magia de suporte para recuperar aliados em confrontos longos.',
    tags: ['cura', 'suporte', 'mana'],
    source: 'OGL',
    payload: { circle: 1, cost: 2 },
  },
  {
    id: 'tormenta20-spell-raio-eletrico',
    systemSlug: 'tormenta20',
    kind: 'SPELL',
    name: 'Raio Eletrico',
    summary: 'Ataque de dano direto com escalonamento para ameaças de medio porte.',
    tags: ['eletrico', 'dano', 'mana'],
    source: 'OGL',
    payload: { circle: 2, cost: 3 },
  },
  {
    id: 'tormenta20-item-pocao-mana',
    systemSlug: 'tormenta20',
    kind: 'ITEM',
    name: 'Pocao de Mana',
    summary: 'Recupera mana de conjuradores durante a aventura.',
    tags: ['mana', 'consumable'],
    source: 'OGL',
    payload: { effect: 'Recupera 1d6 PM' },
  },
  {
    id: 'tormenta20-item-poe-adamantina',
    systemSlug: 'tormenta20',
    kind: 'ITEM',
    name: 'Poeira Adamantina',
    summary: 'Componente raro usado para reforco temporario de equipamento.',
    tags: ['crafting', 'rare', 'material'],
    source: 'OGL',
    payload: { effect: '+1 Defesa por cena' },
  },
  {
    id: 'tormenta20-item-condition-abalado',
    systemSlug: 'tormenta20',
    kind: 'ITEM',
    name: 'Condicao - Abalado',
    summary: 'Estado emocional comprometido com penalidade em testes de acao.',
    tags: ['condition', 'quick-reference', 'mental'],
    source: 'OGL',
    payload: { effect: '-2 em testes de pericia e ataque' },
  },
  {
    id: 'tormenta20-item-rule-acao-padrao-movimento',
    systemSlug: 'tormenta20',
    kind: 'ITEM',
    name: 'Regra Rapida - Acao Padrao e Movimento',
    summary: 'Resumo de economia de acao para acelerar decisao tatica na mesa.',
    tags: ['rule', 'quick-reference', 'combat'],
    source: 'OGL',
    payload: { structure: ['Acao padrao', 'Movimento', 'Acao livre'] },
  },
  {
    id: 'tormenta20-bestiary-troll',
    systemSlug: 'tormenta20',
    kind: 'BESTIARY',
    name: 'Troll',
    summary: 'Monstro robusto com regeneracao perigosa.',
    tags: ['brute', 'regeneration'],
    source: 'OGL',
    payload: { nd: '7', role: 'Brutamontes' },
  },
  {
    id: 'tormenta20-bestiary-lobo-gelido',
    systemSlug: 'tormenta20',
    kind: 'BESTIARY',
    name: 'Lobo Gelido',
    summary: 'Predador de clima extremo, ideal para trilhas e emboscadas de inverno.',
    tags: ['beast', 'cold', 'pack'],
    source: 'OGL',
    payload: { nd: '3', role: 'Assaltante' },
  },
  {
    id: 'tormenta20-bestiary-hidra-menor',
    systemSlug: 'tormenta20',
    kind: 'BESTIARY',
    name: 'Hidra Menor',
    summary: 'Ameaça multipla para batalhas de boss com pressao em area.',
    tags: ['boss', 'multihead', 'swamp'],
    source: 'OGL',
    payload: { nd: '10', role: 'Chefe' },
  },
];

const normalize = (value: string): string => value.trim().toLowerCase();

export const listAvailableCompendiumKinds = (): CompendiumKind[] => {
  return ['BESTIARY', 'SPELL', 'ITEM', 'CLASS'];
};

export const filterCompendiumEntries = (input: FilterCompendiumInput): CompendiumEntry[] => {
  const normalizedSearch = input.search ? normalize(input.search) : '';

  const bySystem = ENTRIES.filter((entry) => entry.systemSlug === input.systemSlug);
  const byKind = input.kind ? bySystem.filter((entry) => entry.kind === input.kind) : bySystem;
  const bySearch = normalizedSearch
    ? byKind.filter((entry) => {
        const haystack = `${entry.name} ${entry.summary} ${entry.tags.join(' ')}`.toLowerCase();
        return haystack.includes(normalizedSearch);
      })
    : byKind;

  return bySearch.slice(0, input.limit);
};

export const getCompendiumKindTotals = (systemSlug: string): Record<CompendiumKind, number> => {
  const systemEntries = ENTRIES.filter((entry) => entry.systemSlug === systemSlug);

  return {
    BESTIARY: systemEntries.filter((entry) => entry.kind === 'BESTIARY').length,
    SPELL: systemEntries.filter((entry) => entry.kind === 'SPELL').length,
    ITEM: systemEntries.filter((entry) => entry.kind === 'ITEM').length,
    CLASS: systemEntries.filter((entry) => entry.kind === 'CLASS').length,
  };
};
